name: Karate UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Karate tests
      run: mvn test -DinnoCloudPostServices=https://cognito-idp.eu-west-2.amazonaws.com/ -DclientId=6prsm50eflpmog3p68mte57iv6 -Dusername=dineshkumar@innocloud.co.in -Dpassword=Dlb0907@@@ || echo suppress-exit-code

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml

    - name: Archive Karate reports
      uses: actions/upload-artifact@v2
      with:
        name: karate-reports
        path: target/karate-reports/*.html

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
