name: Karate UI Tests

on:
  workflow_dispatch:

# env:
#   EMAIL: ${{ secrets.email }}
#   PASSWORD: ${{ secrets.password }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: setup
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.7
        
      - name: mvn install
      - run: mvn clean imstall

      - name: mvn run
      - run: mvn test -Demail=dineshkumar@innocloud.co.in -Dpassword=Dlb0907@@@ -Dheadless=--headless=new
