name: Karate UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Karate tests
      run: mvn test -DinnoCloudPostServices=https://cognito-idp.eu-west-2.amazonaws.com/ -DclientId=6prsm50eflpmog3p68mte57iv6 -Dusername=dineshkumar@innocloud.co.in -Dpassword=Dlb0907@@@

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml

    - name: Archive Karate reports
      uses: actions/upload-artifact@v2
      with:
        name: karate-reports
        path: target/karate-reports/*.html

    - name: Upload Karate reports to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/karate-reports

    - name: Get Commit SHA
      id: vars
      run: echo "::set-output name=sha::${GITHUB_SHA}"

    - name: Comment on Pull Request
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Karate UI Test Report: [View Report](https://${{ github.repository_owner }}.github.io/${{ github.repository }}/karate-reports/karate-summary.html?${{ steps.vars.outputs.sha }})

    - name: Output Report Link
      if: github.event_name != 'pull_request'
      run: echo "Karate UI Test Report:https://${{ github.repository_owner }}.github.io/${{ github.repository }}/karate-reports/karate-summary.html?${{ steps.vars.outputs.sha }}"
